version: "2.1"
# More info at https://jellyfin.org/docs/general/administration/installing.html#docker
# and https://jellyfin.org/docs/index.html
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/shows:/shows
      - ${MEDIA_DIR}/music:/music
